on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  selenium:
    name: 'selenium'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm i
      - run: npx ts-node .\src\tools\runner.ts selenium simple:*
      - run: npx ts-node .\src\tools\runner.ts selenium launch-browser:*