on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  selenium:
    name: 'selenium'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'
      # taken from https://github.com/jfoclpf/autocosts/blob/master/.github/workflows/firefox.yml
      - name: Install Webdriver manager
        run: sudo npm i -g webdriver-manager
      - name: Install browser engines
        run: | 
          sudo webdriver-manager update --out_dir /usr/local/bin
          ls -alF /usr/local/bin
          sudo rm /usr/local/bin/*.zip /usr/local/bin/*.tar.gz
          sudo mv /usr/local/bin/chromedriver* /usr/local/bin/chromedriver
          sudo mv /usr/local/bin/geckodriver* /usr/local/bin/geckodriver
          ls -alF /usr/local/bin/geckodriver /usr/local/bin/chromedriver
      - run: npm i
      - run: npx ts-node ./src/tools/runner.ts selenium simple:screenshot
      - run: npx ts-node ./src/tools/runner.ts selenium simple:pageTitle
      - run: npx ts-node ./src/tools/runner.ts selenium simple:click
      # TODO: fix selenium crashing with "NoSuchSessionError: invalid session id" error
      # - run: npx ts-node ./src/tools/runner.ts selenium simple:*
      # TODO: fix browser launching
      # - run: npx ts-node ./src/tools/runner.ts selenium launch-browser:*